name: Create develop PR auto
on:
  push:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: get_branch
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF#refs/heads/}"

        # FIXME remove fix-ci
      - name: Skip if branch is main or develop or fix-ci
        if: ${{ steps.get_branch.outputs.branch == 'main' || steps.get_branch.outputs.branch == 'develop' || steps.get_branch.outputs.branch == 'fix-ci' }}
        run: exit 0

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Reset promotion branch
        run: |
          git fetch origin ${{ steps.get_branch.outputs.branch }}:${{ steps.get_branch.outputs.branch }}
          git reset --hard ${{ steps.get_branch.outputs.branch }}

      - name: Get issue number from branch name
        id: get_issue
        run: echo number=$(echo ${GITHUB_REF#refs/heads/feature/} | cut -d'-' -f1) >> $GITHUB_OUTPUT

      - name: Fetch issue details
        id: fetch_issue
        run: |
          response=$(curl --request GET --url https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.get_issue.outputs.number }})
          title=$(echo "$response" | jq -r .title)
          if [ $title = "null" ]; then
            title=$(echo ${GITHUB_REF#refs/heads/})
          fi
          echo title=$title >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          title: ${{ steps.fetch_issue.outputs.title }}
          branch: ${{ steps.get_branch.outputs.branch }}
          base: develop
          committer: windybirth
          reviewers: windybirth

      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
